# Generated by Django 2.2.7 on 2019-12-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(max_length=12)),
                ('old_price', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=12)),
                ('picture', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
            ],
        ),
    ]
