# Generated by Django 2.2.7 on 2021-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200814_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_amount',
            field=models.IntegerField(default=10),
        ),
    ]
