# Generated by Django 3.1.7 on 2021-03-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210320_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statues',
            new_name='status',
        ),
    ]
