# Generated by Django 3.1.7 on 2021-03-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210322_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='name name', max_length=200),
            preserve_default=False,
        ),
    ]
