# Generated by Django 3.1.7 on 2021-03-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='0',
            new_name='user',
        ),
    ]
