# Generated by Django 3.1.7 on 2021-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210327_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='address', max_length=200),
            preserve_default=False,
        ),
    ]
