# Generated by Django 2.2.7 on 2019-12-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191228_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='zip',
            field=models.IntegerField(default='00000'),
        ),
    ]
