# Generated by Django 2.2.7 on 2020-01-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='empty-user', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.CharField(max_length=30000),
        ),
    ]
