# Generated by Django 2.2.7 on 2020-02-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200120_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cardName',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
