# Generated by Django 2.2.7 on 2020-02-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_payment_cardname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cardName',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderTime',
            field=models.DateField(auto_now=True),
        ),
    ]
