# Generated by Django 2.2.7 on 2020-02-06 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200206_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTime',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
